name: Busted
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: hishamhm/gh-actions-lua@master
        with:
          luaVersion: "5.4"

      - uses: luarocks/gh-actions-luarocks@master
        with:
          luaRocksVersion: "3.12.2"

      - name: Build
        run: "luarocks build"

      - name: Run Busted
        uses: lunarmodules/busted@v2.2.0
